/**
 * Vocabulário do IMSLP: traduções de gênero, mapeamento de instrumentos,
 * categorias válidas, palavras-chave de tipo de obra e tradução de tonalidade.
 *
 * **Copiado do legado praticamente como estava, e de propósito.** É dado, não
 * lógica: mil linhas de correspondência entre o vocabulário do IMSLP (em
 * inglês) e o da plataforma (em português), construídas ao longo do tempo
 * contra páginas reais. Reescrever isso seria reintroduzir erros que já foram
 * corrigidos uma vez.
 *
 * O que mudou: no legado ele vivia em `scripts/`, fora de `src/`, e era
 * importado pelas rotas com um caminho relativo de seis níveis
 * (`../../../../../../scripts/imslp-works-scraper-util`). Aqui é um módulo do
 * projeto como qualquer outro.
 */

export const WORK_GENRE_TRANSLATIONS: Record<string, string> = {
  adagiettos: 'adagiettos',
  romantic: 'romântico',
  adagios: 'adágios',
  agitatos: 'agitatos',
  'agnus dei': 'agnus dei',
  airs: 'árias',
  allegrettos: 'allegrettos',
  allegros: 'allegros',
  allemandes: 'alemandas',
  andantes: 'andantes',
  andantinos: 'andantinos',
  anglaises: 'inglesas',
  anthems: 'hinos',
  antiphons: 'antífonas',
  arabesques: 'arabescos',
  arias: 'árias',
  ariettas: 'ariettas',
  ariosos: 'ariosos',
  aubades: 'aubadas',
  autobiographies: 'autobiografias',
  'ave maria': 'ave maria',
  bagatelles: 'bagatelas',
  'ballad operas': 'óperas de balada',
  ballades: 'baladas',
  ballads: 'baladas',
  ballatas: 'ballatas',
  ballets: 'balés',
  'ballets heroiques': 'balés heroicos',
  balletti: 'balletti',
  balletts: 'balletts',
  barcarolles: 'barcarolas',
  'basse danses': 'baixas danças',
  beguines: 'beguines',
  benedictus: 'benedictus',
  berceuses: 'canções de ninar',
  bicinia: 'bicínios',
  biographies: 'biografias',
  blues: 'blues',
  boleros: 'boleros',
  'bossa novas': 'bossa novas',
  bourrees: 'bourrees',
  boutades: 'boutadas',
  burlesques: 'burlescos',
  cadenzas: 'cadências',
  cakewalks: 'cakewalks',
  canaries: 'canárias',
  canciones: 'canções',
  canons: 'cânones',
  cantabiles: 'cantábiles',
  cantatas: 'cantatas',
  canticles: 'cânticos',
  cantigas: 'cantigas',
  cantilenas: 'cantilenas',
  canzonas: 'canzonas',
  canzonets: 'canzonets',
  canzonettas: 'canzonettas',
  canzoni: 'canzoni',
  capriccios: 'caprichos',
  caprices: 'caprichos',
  carminas: 'carminas',
  carols: 'cânticos natalinos',
  cassations: 'cassações',
  catalogs: 'catálogos',
  catches: 'catches',
  cavatinas: 'cavatinas',
  chaconnes: 'chaconas',
  chansons: 'chansons',
  chants: 'cantos',
  'character pieces': 'peças de caráter',
  choralbearbeitungen: 'elaborações corais',
  'chorale preludes': 'prelúdios de coral',
  chorales: 'corais',
  chorinhos: 'chorinhos',
  choruses: 'coros',
  'comic operas': 'óperas cômicas',
  communions: 'comunhões',
  concertantes: 'concertantes',
  'concerti grossi': 'concertos grossos',
  concertinos: 'concertinos',
  concertos: 'concertos',
  conductus: 'conductus',
  congas: 'congas',
  correspondence: 'correspondência',
  corteges: 'cortejos',
  'country dances': 'danças campestres',
  courantes: 'courantes',
  credo: 'credo',
  'critical editions': 'edições críticas',
  czardas: 'czardas',
  dances: 'danças',
  danzas: 'danças',
  danzon: 'danzón',
  decets: 'decetos',
  descants: 'descantes',
  dictionaries: 'dicionários',
  'dies irae': 'dies irae',
  dirges: 'lamentos',
  divertimentos: 'divertimentos',
  divertissements: 'divertissements',
  divisions: 'divisões',
  'double canons': 'cânones duplos',
  'double fugues': 'fugas duplas',
  duets: 'duetos',
  duettinos: 'duettinos',
  dumkas: 'dumkas',
  eclogues: 'éclogas',
  ecossaises: 'escocesas',
  elegies: 'elegias',
  epithalamia: 'epitalâmios',
  equali: 'equali',
  estampies: 'estampies',
  ethnomusicology: 'etnomusicologia',
  exercises: 'exercícios',
  'fairy operas': 'óperas de fadas',
  fancies: 'fantasias',
  fandangos: 'fandangos',
  fanfares: 'fanfarras',
  fantasias: 'fantasias',
  farces: 'farsas',
  'film scores': 'trilhas sonoras',
  finales: 'finais',
  flourishes: 'floreios',
  'folk operas': 'óperas folclóricas',
  folksongs: 'canções folclóricas',
  forlanes: 'forlanas',
  foxtrots: 'foxtrots',
  frottolas: 'frottolas',
  fugatos: 'fugatos',
  fughettas: 'fughettas',
  fugues: 'fugas',
  'funeral marches': 'marchas fúnebres',
  'funeral music': 'música fúnebre',
  furiants: 'furiants',
  galliards: 'galhardas',
  galops: 'galopes',
  gavottes: 'gavotas',
  gigues: 'gigas',
  glees: 'glees',
  gloria: 'glória',
  graduals: 'graduais',
  'grand operas': 'grandes óperas',
  grounds: 'grounds',
  guajiras: 'guajiras',
  habaneras: 'habaneras',
  harmonies: 'harmonias',
  hornpipes: 'hornpipes',
  humoresques: 'humorescos',
  hymns: 'hinos',
  impromptus: 'impromptus',
  improperia: 'impropérios',
  improvisations: 'improvisações',
  'in nomines': 'in nomines',
  'incidental music': 'música incidental',
  interludes: 'interlúdios',
  intermedes: 'intermédios',
  intermezzos: 'intermezzos',
  interviews: 'entrevistas',
  intonations: 'entoações',
  intradas: 'intradas',
  introductions: 'introduções',
  introits: 'introitos',
  inventions: 'invenções',
  jacaras: 'jácaras',
  jazz: 'jazz',
  jotas: 'jotas',
  krakowiaks: 'krakowiaks',
  kritis: 'kritis',
  kujawiaks: 'kujawiaks',
  kyrie: 'kyrie',
  lamentations: 'lamentações',
  landler: 'ländler',
  larghettos: 'larghettos',
  largos: 'largos',
  lentos: 'lentos',
  lessons: 'lições',
  librettos: 'libretos',
  lieder: 'lieder',
  litanies: 'litanias',
  liturgies: 'liturgias',
  lullabies: 'canções de ninar',
  'lyric comedies': 'comédias líricas',
  'lyric dramas': 'dramas líricos',
  'lyric operas': 'óperas líricas',
  'lyric tragedies': 'tragédias líricas',
  madrigals: 'madrigais',
  magnificats: 'magnificats',
  malaguenas: 'malagueñas',
  marches: 'marchas',
  masques: 'máscaras',
  masses: 'missas',
  mazurkas: 'mazurcas',
  meditations: 'meditações',
  medleys: 'medleys',
  melodies: 'melodias',
  melodramas: 'melodramas',
  methods: 'métodos',
  milongas: 'milongas',
  minuets: 'minuetos',
  miserere: 'miserere',
  moderatos: 'moderatos',
  modern: 'moderno',
  monodramas: 'monodramas',
  motets: 'motetos',
  movements: 'movimentos',
  musettes: 'musettes',
  musicals: 'musicais',
  nocturnes: 'noturnos',
  nonets: 'nonetos',
  octets: 'octetos',
  odes: 'odes',
  offertories: 'ofertórios',
  offertorium: 'ofertório',
  'opera buffa': 'ópera buffa',
  'opera semiseria': 'ópera semiseria',
  'opera seria': 'ópera seria',
  'opera-ballets': 'óperas-balé',
  operas: 'óperas',
  'operas bouffes': 'óperas bouffes',
  'operas comiques': 'óperas cômicas',
  operettas: 'operetas',
  'operettes bouffes': 'operetas bouffes',
  oratorios: 'oratórios',
  orchestration: 'orquestração',
  organology: 'organologia',
  ostinatos: 'ostinatos',
  overtures: 'aberturas',
  pantomimes: 'pantomimas',
  paraphrases: 'paráfrases',
  partimenti: 'partimenti',
  partitas: 'partitas',
  paseos: 'paseos',
  pasodobles: 'pasodobles',
  pasos: 'pasos',
  passacaglias: 'passacaglias',
  passamezzos: 'passamezzos',
  passepieds: 'passepieds',
  passions: 'paixões',
  pasticcios: 'pasticcios',
  'pastoral operas': 'óperas pastorais',
  pastorales: 'pastorais',
  pavans: 'pavanas',
  'performance practice': 'prática interpretativa',
  plainchant: 'cantochão',
  polkas: 'polcas',
  polonaises: 'polonesas',
  postludes: 'poslúdios',
  potpourris: 'potpourris',
  praeambula: 'preâmbulos',
  preludes: 'prelúdios',
  prestos: 'prestos',
  processionals: 'processionais',
  prologues: 'prólogos',
  psalms: 'salmos',
  'publishers catalogs': 'catálogos de editores',
  quadrilles: 'quadrilhas',
  quartets: 'quartetos',
  quartettinos: 'quartettinos',
  quicksteps: 'quicksteps',
  quintets: 'quintetos',
  quintettinos: 'quintettinos',
  quodlibets: 'quodlibets',
  rags: 'rags',
  recessionals: 'recessivos',
  recitatives: 'recitativos',
  recits: 'récits',
  'religious works': 'obras religiosas',
  requiems: 'réquiens',
  responsories: 'responsórios',
  revues: 'revistas',
  rhapsodies: 'rapsódias',
  ricercars: 'ricercares',
  rigaudons: 'rigaudons',
  ritournelles: 'ritornelos',
  romances: 'romances',
  rondeaux: 'rondeaux',
  rondinos: 'rondinos',
  rondolettos: 'rondolettos',
  rondos: 'rondós',
  rounds: 'rounds',
  rumbas: 'rumbas',
  'sacred cantatas': 'cantatas sacras',
  'sacred choruses': 'coros sacros',
  'sacred concertos': 'concertos sacros',
  'sacred hymns': 'hinos sacros',
  'sacred oratorios': 'oratórios sacros',
  'sacred songs': 'canções sacras',
  saltarellos: 'saltarelos',
  'salve regina': 'salve regina',
  sambas: 'sambas',
  sanctus: 'sanctus',
  sarabandes: 'sarabandas',
  sardanas: 'sardanas',
  'savoy operas': 'óperas savoy',
  'scales and patterns': 'escalas e padrões',
  scherzos: 'scherzos',
  'secular cantatas': 'cantatas seculares',
  'secular choruses': 'coros seculares',
  'secular hymns': 'hinos seculares',
  'secular oratorios': 'oratórios seculares',
  seguidillas: 'seguidillas',
  septets: 'septetos',
  sequences: 'sequências',
  serenades: 'serenatas',
  serenatas: 'serenatas',
  services: 'serviços',
  sevillanas: 'sevilhanas',
  sextets: 'sextetos',
  sicilianas: 'sicilianas',
  sinfonias: 'sinfonias',
  sinfoniettas: 'sinfoniettas',
  singspiele: 'singspiels',
  sketches: 'esboços',
  solfeggios: 'solfegios',
  sonatas: 'sonatas',
  sonatinas: 'sonatinas',
  sonatinettas: 'sonatinettas',
  sones: 'sones',
  songs: 'canções',
  sousedsky: 'sousedsky',
  spirituals: 'spirituals',
  'stabat mater': 'stabat mater',
  studies: 'estudos',
  suites: 'suítes',
  'symphonic poems': 'poemas sinfônicos',
  symphonies: 'sinfonias',
  'symphonies concertantes': 'sinfonias concertantes',
  tambourins: 'tamborins',
  tangos: 'tangos',
  tarantellas: 'tarantelas',
  'te deum': 'te deum',
  terzettinos: 'terzettinos',
  'theatrical works': 'obras teatrais',
  'thematic catalogs': 'catálogos temáticos',
  threnodies: 'trenódias',
  tientos: 'tientos',
  toccatas: 'tocatas',
  tombeaux: 'tombeaux',
  tonadillas: 'tonadillas',
  'tragedies en musique': 'tragédias em música',
  trios: 'trios',
  tyroliennes: 'tirolesas',
  'uncategorized pages': 'páginas sem categoria',
  variations: 'variações',
  varnams: 'varnams',
  vaudevilles: 'vaudevilles',
  'verismo operas': 'óperas veristas',
  versets: 'versetos',
  vespers: 'vésperas',
  villancicos: 'villancicos',
  villanelle: 'villanela',
  villanelles: 'villanelas',
  vivaces: 'vivaces',
  vocalises: 'vocalizos',
  volte: 'voltas',
  voluntaries: 'voluntários',
  waltzes: 'valsas',
  waltz: 'valsas',
  'wedding marches': 'marchas nupciais',
  'wedding music': 'música de casamento',
  writings: 'escritos',
  zarzuelas: 'zarzuelas',
  zortzicos: 'zortzicos',
  zwiefache: 'zwiefache',
  fantasies: 'fantasias',
  etudes: 'estudos',
  'not defined': 'não definido',
};

// Set de gêneros válidos em inglês (mantém o original)
export const VALID_WORKGENRES = new Set([
  'adagiettos',
  'romantic',
  'adagios',
  'agitatos',
  'agnus dei',
  'airs',
  'allegrettos',
  'allegros',
  'allemandes',
  'andantes',
  'andantinos',
  'anglaises',
  'anthems',
  'antiphons',
  'arabesques',
  'arias',
  'ariettas',
  'ariosos',
  'aubades',
  'autobiographies',
  'ave maria',
  'bagatelles',
  'ballad operas',
  'ballades',
  'ballads',
  'ballatas',
  'ballets',
  'ballets heroiques',
  'balletti',
  'balletts',
  'barcarolles',
  'basse danses',
  'beguines',
  'benedictus',
  'berceuses',
  'bicinia',
  'biographies',
  'blues',
  'boleros',
  'bossa novas',
  'bourrees',
  'boutades',
  'burlesques',
  'cadenzas',
  'cakewalks',
  'canaries',
  'canciones',
  'canons',
  'cantabiles',
  'cantatas',
  'canticles',
  'cantigas',
  'cantilenas',
  'canzonas',
  'canzonets',
  'canzonettas',
  'canzoni',
  'capriccios',
  'caprices',
  'carminas',
  'carols',
  'cassations',
  'catalogs',
  'catches',
  'cavatinas',
  'chaconnes',
  'chansons',
  'chants',
  'character pieces',
  'choralbearbeitungen',
  'chorale preludes',
  'chorales',
  'chorinhos',
  'choruses',
  'comic operas',
  'communions',
  'concertantes',
  'concerti grossi',
  'concertinos',
  'concertos',
  'conductus',
  'congas',
  'correspondence',
  'corteges',
  'country dances',
  'courantes',
  'credo',
  'critical editions',
  'czardas',
  'dances',
  'danzas',
  'danzon',
  'decets',
  'descants',
  'dictionaries',
  'dies irae',
  'dirges',
  'divertimentos',
  'divertissements',
  'divisions',
  'double canons',
  'double fugues',
  'duets',
  'duettinos',
  'dumkas',
  'eclogues',
  'ecossaises',
  'elegies',
  'epithalamia',
  'equali',
  'estampies',
  'etudes',
  'etude',
  'ethnomusicology',
  'exercises',
  'fairy operas',
  'fancies',
  'fandangos',
  'fanfares',
  'fantasias',
  'farces',
  'film scores',
  'finales',
  'flourishes',
  'folk operas',
  'folksongs',
  'forlanes',
  'foxtrots',
  'frottolas',
  'fugatos',
  'fughettas',
  'fugues',
  'funeral marches',
  'funeral music',
  'furiants',
  'galliards',
  'galops',
  'gavottes',
  'gigues',
  'glees',
  'gloria',
  'graduals',
  'grand operas',
  'grounds',
  'guajiras',
  'habaneras',
  'harmonies',
  'hornpipes',
  'humoresques',
  'hymns',
  'impromptus',
  'improperia',
  'improvisations',
  'in nomines',
  'incidental music',
  'interludes',
  'intermedes',
  'intermezzos',
  'interviews',
  'intonations',
  'intradas',
  'introductions',
  'introits',
  'inventions',
  'jacaras',
  'jazz',
  'jotas',
  'krakowiaks',
  'kritis',
  'kujawiaks',
  'kyrie',
  'lamentations',
  'landler',
  'larghettos',
  'largos',
  'lentos',
  'lessons',
  'librettos',
  'lieder',
  'litanies',
  'liturgies',
  'lullabies',
  'lyric comedies',
  'lyric dramas',
  'lyric operas',
  'lyric tragedies',
  'madrigals',
  'magnificats',
  'malaguenas',
  'marches',
  'masques',
  'masses',
  'mazurkas',
  'meditations',
  'medleys',
  'melodies',
  'melodramas',
  'methods',
  'milongas',
  'minuets',
  'miserere',
  'moderatos',
  'modern',
  'monodramas',
  'motets',
  'movements',
  'musettes',
  'musicals',
  'nocturnes',
  'nonets',
  'octets',
  'odes',
  'offertories',
  'offertorium',
  'opera buffa',
  'opera semiseria',
  'opera seria',
  'opera-ballets',
  'operas',
  'operas bouffes',
  'operas comiques',
  'operettas',
  'operettes bouffes',
  'oratorios',
  'orchestration',
  'organology',
  'ostinatos',
  'overtures',
  'pantomimes',
  'paraphrases',
  'partimenti',
  'partitas',
  'paseos',
  'pasodobles',
  'pasos',
  'passacaglias',
  'passamezzos',
  'passepieds',
  'passions',
  'pasticcios',
  'pastoral operas',
  'pastorales',
  'pavans',
  'performance practice',
  'pieces',
  'plainchant',
  'polkas',
  'polonaises',
  'postludes',
  'potpourris',
  'praeambula',
  'preludes',
  'prestos',
  'processionals',
  'prologues',
  'psalms',
  'publishers catalogs',
  'quadrilles',
  'quartets',
  'quartettinos',
  'quicksteps',
  'quintets',
  'quintettinos',
  'quodlibets',
  'rags',
  'recessionals',
  'recitatives',
  'recits',
  'religious works',
  'requiems',
  'responsories',
  'revues',
  'rhapsodies',
  'ricercars',
  'rigaudons',
  'ritournelles',
  'romances',
  'rondeaux',
  'rondinos',
  'rondolettos',
  'rondos',
  'rounds',
  'rumbas',
  'sacred cantatas',
  'sacred choruses',
  'sacred concertos',
  'sacred hymns',
  'sacred oratorios',
  'sacred songs',
  'saltarellos',
  'salve regina',
  'sambas',
  'sanctus',
  'sarabandes',
  'sardanas',
  'savoy operas',
  'scales and patterns',
  'scherzos',
  'secular cantatas',
  'secular choruses',
  'secular hymns',
  'secular oratorios',
  'seguidillas',
  'septets',
  'sequences',
  'serenades',
  'serenatas',
  'services',
  'sevillanas',
  'sextets',
  'sicilianas',
  'sinfonias',
  'sinfoniettas',
  'singspiele',
  'sketches',
  'solfeggios',
  'sonatas',
  'sonatinas',
  'sonatinettas',
  'sones',
  'songs',
  'sousedsky',
  'spirituals',
  'stabat mater',
  'studies',
  'suites',
  'symphonic poems',
  'symphonies',
  'symphonies concertantes',
  'tambourins',
  'tangos',
  'tarantellas',
  'te deum',
  'terzettinos',
  'theatrical works',
  'thematic catalogs',
  'threnodies',
  'tientos',
  'toccatas',
  'tombeaux',
  'tonadillas',
  'tragedies en musique',
  'trios',
  'tyroliennes',
  'uncategorized pages',
  'variations',
  'varnams',
  'vaudevilles',
  'verismo operas',
  'versets',
  'vespers',
  'villancicos',
  'villanelle',
  'villanelles',
  'vivaces',
  'vocalises',
  'volte',
  'voluntaries',
  'waltzes',
  'waltz',
  'wedding marches',
  'wedding music',
  'writings',
  'zarzuelas',
  'zortzicos',
  'zwiefache',

  'not defined',
]);

export const VALID_PORTUGUESE_WORKGENRES = new Set(
  Object.values(WORK_GENRE_TRANSLATIONS),
);

export const INSTRUMENT_MAPPING: Record<string, string> = {
  // Instrumentos de cordas
  violin: 'Violino',
  viola: 'Viola',
  cello: 'Violoncelo',
  'double bass': 'Contrabaixo',
  bass: 'Contrabaixo',
  guitar: 'Violão',
  harp: 'Harpa',
  mandolin: 'Bandolim',
  banjo: 'Banjo',
  lute: 'Alaúde',
  'string quartet': 'Quarteto de Cordas',
  'string orchestra': 'Orquestra de Cordas',
  strings: 'Cordas',

  // Piano e teclados
  piano: 'Piano',
  'piano 4-hands': 'Piano 4-mãos',
  'piano duet': 'Piano a Quatro Mãos',
  'piano duo': 'Piano Duo',
  '2 pianos': '2 Pianos',
  harpsichord: 'Cravo',
  organ: 'Órgão',
  harmonium: 'Harmônio',
  celesta: 'Celesta',
  keyboard: 'Teclado',

  // Instrumentos de sopro - madeiras
  flute: 'Flauta',
  piccolo: 'Flautim',
  oboe: 'Oboé',
  'english horn': 'Corne Inglês',
  clarinet: 'Clarinete',
  'bass clarinet': 'Clarinete Baixo',
  bassoon: 'Fagote',
  contrabassoon: 'Contrafagote',
  saxophone: 'Saxofone',
  recorder: 'Flauta Doce',
  woodwinds: 'Madeiras',

  // Instrumentos de sopro - metais
  trumpet: 'Trompete',
  horn: 'Trompa',
  'french horn': 'Trompa Francesa',
  trombone: 'Trombone',
  tuba: 'Tuba',
  cornet: 'Corneta',
  flugelhorn: 'Fliscorne',
  euphonium: 'Eufônio',
  brass: 'Metais',

  // Percussão
  timpani: 'Tímpanos',
  drums: 'Bateria',
  percussion: 'Percussão',
  xylophone: 'Xilofone',
  marimba: 'Marimba',
  vibraphone: 'Vibrafone',
  triangle: 'Triângulo',
  cymbals: 'Pratos',
  tambourine: 'Pandeiro',
  'snare drum': 'Caixa',
  'bass drum': 'Bumbo',
  bells: 'Sinos',
  chimes: 'Carrilhão',
  gong: 'Gongo',

  // Vozes
  voice: 'Voz',
  soprano: 'Soprano',
  alto: 'Contralto',
  tenor: 'Tenor',
  baritone: 'Barítono',
  'mezzo-soprano': 'Meio-soprano',
  choir: 'Coro',
  chorus: 'Coro',
  vocal: 'Vocal',
  'mixed choir': 'Coro Misto',
  'male choir': 'Coro Masculino',
  'female choir': 'Coro Feminino',
  "children's choir": 'Coro Infantil',

  // Conjuntos
  orchestra: 'Orquestra',
  'orchestra;': 'Orquestra',
  'chamber orchestra': 'Orquestra de Câmara',
  'symphony orchestra': 'Orquestra Sinfônica',
  'philharmonic orchestra': 'Orquestra Filarmônica',
  band: 'Banda',
  'wind band': 'Banda de Sopros',
  'brass band': 'Banda de Metais',
  'jazz band': 'Banda de Jazz',
  ensemble: 'Conjunto',
  'chamber ensemble': 'Conjunto de Câmara',
  'wind ensemble': 'Conjunto de Sopros',

  // Música de câmara
  solo: 'Solo',
  duet: 'Duo',
  trio: 'Trio',
  quartet: 'Quarteto',
  quintet: 'Quinteto',
  sextet: 'Sexteto',
  septet: 'Septeto',
  octet: 'Octeto',
  nonet: 'Noneto',
  decet: 'Deceto',

  // Instrumentos tradicionais/folclóricos
  bagpipes: 'Gaita de Foles',
  accordion: 'Acordeão',
  harmonica: 'Gaita',
  concertina: 'Concertina',
  dulcimer: 'Saltério',
  zither: 'Cítara',
  sitar: 'Cítara Indiana',
  tabla: 'Tabla',

  // Termos técnicos
  continuo: 'Baixo Contínuo',
  'basso continuo': 'Baixo Contínuo',
  'figured bass': 'Baixo Cifrado',
  accompaniment: 'Acompanhamento',
  unaccompanied: 'Sem Acompanhamento',
  'a cappella': 'A Cappella',
  with: 'com',
  and: 'e',
  or: 'ou',
  optional: 'Opcional',
  'ad libitum': 'Ad Libitum',

  parts: 'partes',
  voices: 'vozes',
};

export const VALID_CATEGORIES: Record<string, string> = {
  // Peças gerais
  Pieces: 'Peças',
  Works: 'Obras',
  Compositions: 'Composições',

  // Solo piano
  'For piano (arr)': 'Arranjo para piano',
  'For piano 3 hands': 'Para piano 3 mãos',
  'For piano 4 hands': 'Para piano 4 mãos',
  'For piano 4 hands (arr)': 'Arranjo para piano 4 mãos',

  'For 2 pianos': 'Para 2 pianos',
  'For 2 pianos (arr)': 'Arranjo para 2 pianos',

  // Piano e orquestra
  'For piano, orchestra': 'Para piano e orquestra',
  'For piano, orchestra (arr)': 'Arranjo para piano e orquestra',
  'For 2 pianos, orchestra': 'Para 2 pianos e orquestra',

  // Número de players/instrumentistas
  'For 1 player': 'Para 1 instrumentista',
  'For 2 players': 'Para 2 instrumentistas',
  'For 3 players': 'Para 3 instrumentistas',
  'For 4 players': 'Para 4 instrumentistas',
  'For 5 players': 'Para 5 instrumentistas',
  'For 6 players': 'Para 6 instrumentistas',
  'For 7 players': 'Para 7 instrumentistas',
  'For 8 players': 'Para 8 instrumentistas',
  'For 9 players': 'Para 9 instrumentistas',
  'For 10 players': 'Para 10 instrumentistas',

  // Arranjos por número de players
  'For 1 player (arr)': 'Arranjo para 1 instrumentista',
  'For 2 players (arr)': 'Arranjo para 2 instrumentistas',
  'For 3 players (arr)': 'Arranjo para 3 instrumentistas',
  'For 4 players (arr)': 'Arranjo para 4 instrumentistas',
  'For 5 players (arr)': 'Arranjo para 5 instrumentistas',
  'For 6 players (arr)': 'Arranjo para 6 instrumentistas',
  'For 7 players (arr)': 'Arranjo para 7 instrumentistas',
  'For 8 players (arr)': 'Arranjo para 8 instrumentistas',
};

export const NORMALIZED_CATEGORIES = Object.entries(VALID_CATEGORIES).reduce<
  Record<string, string>
>((acc, [key, value]) => {
  acc[key.toLowerCase().trim()] = value;
  return acc;
}, {});

export const WORK_TYPE_KEYWORDS = {
  COLLECTION: [
    'complete',
    'all',
    'entire',
    'collection',
    'set',
    'book',
    'completo',
    'todos',
    'inteiro',
    'coleção',
    'conjunto',
    'livro',
  ],
  ARRANGEMENT: [
    'arrangement',
    'transcription',
    'adaptation',
    'version',
    'arranjo',
    'transcrição',
    'adaptação',
    'versão',
  ],
  INDIVIDUAL: [
    'no.',
    'nº',
    'op.',
    'piece',
    'movement',
    'mvt.',
    'peça',
    'movimento',
    'mov.',
  ],
};

export const NOTE_TRANSLATIONS: Record<string, string> = {
  C: 'Dó',
  'C#': 'Dó#',
  'C-sharp': 'Dó#',
  Db: 'Réb',
  'D-flat': 'Réb',
  D: 'Ré',
  'D#': 'Ré#',
  'D-sharp': 'Ré#',
  Eb: 'Mib',
  'E-flat': 'Mib',
  E: 'Mi',
  F: 'Fá',
  'F#': 'Fá#',
  'F-sharp': 'Fá#',
  Gb: 'Solb',
  'G-flat': 'Solb',
  G: 'Sol',
  'G#': 'Sol#',
  'G-sharp': 'Sol#',
  Ab: 'Láb',
  'A-flat': 'Láb',
  A: 'Lá',
  'A#': 'Lá#',
  'A-sharp': 'Lá#',
  Bb: 'Sib',
  'B-flat': 'Sib',
  B: 'Si',
};

// Mapeamento de qualidades tonais
export const MODE_TRANSLATIONS: Record<string, string> = {
  major: 'maior',
  minor: 'menor',
  maj: 'maior',
  min: 'menor',
  M: 'maior',
  m: 'menor',
  Major: 'maior',
  Minor: 'menor',
  MAJOR: 'maior',
  MINOR: 'menor',
};
